# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 624)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.listWidgetQuestions = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetQuestions.setObjectName("listWidgetQuestions")
        self.verticalLayout.addWidget(self.listWidgetQuestions)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditQuestionText = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditQuestionText.setObjectName("lineEditQuestionText")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditQuestionText)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditAnswer1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAnswer1.setObjectName("lineEditAnswer1")
        self.gridLayout.addWidget(self.lineEditAnswer1, 0, 0, 1, 1)
        self.lineEditAnswer2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAnswer2.setObjectName("lineEditAnswer2")
        self.gridLayout.addWidget(self.lineEditAnswer2, 0, 1, 1, 1)
        self.lineEditAnswer3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAnswer3.setObjectName("lineEditAnswer3")
        self.gridLayout.addWidget(self.lineEditAnswer3, 1, 0, 1, 1)
        self.lineEditAnswer4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAnswer4.setObjectName("lineEditAnswer4")
        self.gridLayout.addWidget(self.lineEditAnswer4, 1, 1, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditCorrectAnswer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCorrectAnswer.setObjectName("lineEditCorrectAnswer")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditCorrectAnswer)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout_2.addWidget(self.pushButtonAdd, 0, 0, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout_2.addWidget(self.pushButtonSave, 0, 1, 1, 1)
        self.pushButtonDel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDel.setEnabled(False)
        self.pushButtonDel.setObjectName("pushButtonDel")
        self.gridLayout_2.addWidget(self.pushButtonDel, 0, 2, 1, 1)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Список вопросов:"))
        self.label.setText(_translate("MainWindow", "Текст вопроса:"))
        self.label_2.setText(_translate("MainWindow", "Ответы:"))
        self.label_3.setText(_translate("MainWindow", "Ответ:"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Добавить"))
        self.pushButtonSave.setText(_translate("MainWindow", "Сохранить"))
        self.pushButtonDel.setText(_translate("MainWindow", "Удалить"))
